CREATE DATABASE IF NOT EXISTS monochan;

USE monochan;

CREATE TABLE IF NOT EXISTS Threads (
  ThreadId    INT AUTO_INCREMENT PRIMARY KEY,
  Board       VARCHAR(255) NOT NULL,
	ThreadTitle VARCHAR(255),
	ThreadBody  TEXT,
	ThreadImg   VARCHAR(255) NOT NULL,
  CreatedAt   TIMESTAMP NOT NULL,
  BumpedAt    TIMESTAMP
);

CREATE TABLE IF NOT EXISTS Posts (
  PostId    INT AUTO_INCREMENT PRIMARY KEY,
	PostTitle VARCHAR(255),
	PostBody  VARCHAR(255),
	PostImg   VARCHAR(255),
	CreatedAt DATETIME NOT NULL,
  ThreadId  INT NOT NULL,
  FOREIGN KEY (ThreadId) REFERENCES Threads(ThreadId) ON DELETE CASCADE
);

INSERT INTO Threads (Board, ThreadTitle, ThreadBody, ThreadImg, CreatedAt, BumpedAt) VALUES 
  ("b", "TESTANDO TITULO DE THREAD 1", "TESTANDO THREAD BODY 1", "img1.jpg", NOW(), NOW()),
  ("b", "TESTANDO TITULO DE THREAD 2", "TESTANDO THREAD BODY 2", "img2.jpg", NOW(), NOW()),
  ("b", "TESTANDO TITULO DE THREAD 3", "TESTANDO THREAD BODY 3", "img3.jpg", NOW(), NOW()),
  ("b", "TESTANDO TITULO DE THREAD 4", "TESTANDO THREAD BODY 4", "img4.gif", NOW(), NOW());

INSERT INTO Posts (PostTitle, PostBody, PostImg, CreatedAt, ThreadId) VALUES
  ("TITULO DE POST 1", "POST BODY 1", "POST IMAGE 1", NOW(), 1),
  ("TITULO DE POST 2", "POST BODY 2", "POST IMAGE 2", NOW(), 1),
  ("TITULO DE POST 3", "POST BODY 3", "POST IMAGE 3", NOW(), 2),
  ("TITULO DE POST 4", "POST BODY 4", "POST IMAGE 4", NOW(), 4),
  ("TITULO DE POST 5", "POST BODY 5", "POST IMAGE 5", NOW(), 4);